# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfs.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\x12\x03\x64\x66s\"3\n\x11StoreChunkRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"6\n\x12StoreChunkResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\t\"(\n\x14RetrieveChunkRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\"\x19\n\tChunkData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"&\n\x12\x44\x65leteChunkRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\"%\n\x13\x44\x65leteChunkResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x85\x02\n\x0c\x43hunkService\x12=\n\nStoreChunk\x12\x16.dfs.StoreChunkRequest\x1a\x17.dfs.StoreChunkResponse\x12<\n\rRetrieveChunk\x12\x19.dfs.RetrieveChunkRequest\x1a\x0e.dfs.ChunkData0\x01\x12@\n\x0b\x44\x65leteChunk\x12\x17.dfs.DeleteChunkRequest\x1a\x18.dfs.DeleteChunkResponse\x12\x36\n\x0bHealthCheck\x12\x12.dfs.HealthRequest\x1a\x13.dfs.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STORECHUNKREQUEST']._serialized_start=18
  _globals['_STORECHUNKREQUEST']._serialized_end=69
  _globals['_STORECHUNKRESPONSE']._serialized_start=71
  _globals['_STORECHUNKRESPONSE']._serialized_end=125
  _globals['_RETRIEVECHUNKREQUEST']._serialized_start=127
  _globals['_RETRIEVECHUNKREQUEST']._serialized_end=167
  _globals['_CHUNKDATA']._serialized_start=169
  _globals['_CHUNKDATA']._serialized_end=194
  _globals['_DELETECHUNKREQUEST']._serialized_start=196
  _globals['_DELETECHUNKREQUEST']._serialized_end=234
  _globals['_DELETECHUNKRESPONSE']._serialized_start=236
  _globals['_DELETECHUNKRESPONSE']._serialized_end=273
  _globals['_HEALTHREQUEST']._serialized_start=275
  _globals['_HEALTHREQUEST']._serialized_end=290
  _globals['_HEALTHRESPONSE']._serialized_start=292
  _globals['_HEALTHRESPONSE']._serialized_end=324
  _globals['_CHUNKSERVICE']._serialized_start=327
  _globals['_CHUNKSERVICE']._serialized_end=588
# @@protoc_insertion_point(module_scope)
