# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import dfs_pb2 as dfs__pb2



class ChunkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreChunk = channel.unary_unary(
                '/dfs.ChunkService/StoreChunk',
                request_serializer=dfs__pb2.StoreChunkRequest.SerializeToString,
                response_deserializer=dfs__pb2.StoreChunkResponse.FromString,
                )
        self.RetrieveChunk = channel.unary_stream(
                '/dfs.ChunkService/RetrieveChunk',
                request_serializer=dfs__pb2.RetrieveChunkRequest.SerializeToString,
                response_deserializer=dfs__pb2.ChunkData.FromString,
                )
        self.DeleteChunk = channel.unary_unary(
                '/dfs.ChunkService/DeleteChunk',
                request_serializer=dfs__pb2.DeleteChunkRequest.SerializeToString,
                response_deserializer=dfs__pb2.DeleteChunkResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/dfs.ChunkService/HealthCheck',
                request_serializer=dfs__pb2.HealthRequest.SerializeToString,
                response_deserializer=dfs__pb2.HealthResponse.FromString,
                )


class ChunkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChunkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreChunk,
                    request_deserializer=dfs__pb2.StoreChunkRequest.FromString,
                    response_serializer=dfs__pb2.StoreChunkResponse.SerializeToString,
            ),
            'RetrieveChunk': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveChunk,
                    request_deserializer=dfs__pb2.RetrieveChunkRequest.FromString,
                    response_serializer=dfs__pb2.ChunkData.SerializeToString,
            ),
            'DeleteChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChunk,
                    request_deserializer=dfs__pb2.DeleteChunkRequest.FromString,
                    response_serializer=dfs__pb2.DeleteChunkResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=dfs__pb2.HealthRequest.FromString,
                    response_serializer=dfs__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.ChunkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChunkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dfs.ChunkService/StoreChunk',
            dfs__pb2.StoreChunkRequest.SerializeToString,
            dfs__pb2.StoreChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dfs.ChunkService/RetrieveChunk',
            dfs__pb2.RetrieveChunkRequest.SerializeToString,
            dfs__pb2.ChunkData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dfs.ChunkService/DeleteChunk',
            dfs__pb2.DeleteChunkRequest.SerializeToString,
            dfs__pb2.DeleteChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dfs.ChunkService/HealthCheck',
            dfs__pb2.HealthRequest.SerializeToString,
            dfs__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
